// Third-party notices generated by tools/notices (`pnpm --filter @skepi/notices generate`): the
// JavaScript, Rust and native components this app ships, with their licence files.
import raw from '../generated/third-party-notices.json';

export interface NoticeComponent {
  ecosystem: 'npm' | 'cargo' | 'maven' | 'native';
  name: string;
  version: string;
  license: string;
  url: string;
  texts: string[];
}

export const NOTICES = raw as unknown as { components: NoticeComponent[]; texts: Record<string, string> };

export function noticeCounts(): { components: number; npm: number; cargo: number; maven: number; native: number } {
  const by = (e: NoticeComponent['ecosystem']): number => NOTICES.components.filter((c) => c.ecosystem === e).length;
  return { components: NOTICES.components.length, npm: by('npm'), cargo: by('cargo'), maven: by('maven'), native: by('native') };
}

/** App version from tauri.conf.json (vite.config.ts `define`). */
export const APP_VERSION: string = __SKEPI_VERSION__;
