// Generated by scripts/export-preview.ts from the full cards. Do not edit.
// Developer Preview builds bundle these cards (src/preview.ts): titles, topics, keywords and review
// status only, no step text.
import type { EmergencyCard } from './schema';

export const PREVIEW_CARDS: readonly EmergencyCard[] = [
  {
    "id": "cpr",
    "topics": [
      "cpr",
      "drowning"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "CPR: unresponsive and not breathing (adult)",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "cpr",
          "resuscitation",
          "cardiac arrest",
          "not breathing",
          "unconscious",
          "unresponsive",
          "chest compressions",
          "aed",
          "defibrillator",
          "drowning"
        ]
      },
      "el": {
        "title": "ΚΑΡΠΑ: δεν αντιδρά και δεν αναπνέει (ενήλικας)",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "καρπα",
          "αναζωογονηση",
          "ανακοπη",
          "δεν αναπνεει",
          "αναισθητος",
          "αναισθητη",
          "θωρακικες συμπιεσεις",
          "απινιδωτης",
          "πνιγμος"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "bleeding",
    "topics": [
      "bleeding"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Severe bleeding",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "bleeding",
          "bleed",
          "haemorrhage",
          "hemorrhage",
          "tourniquet",
          "wound",
          "stop the bleed"
        ]
      },
      "el": {
        "title": "Σοβαρή αιμορραγία",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "αιμορραγια",
          "αιμορραγει",
          "τουρνικε",
          "ισχαιμος",
          "αιμοστασ"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "choking",
    "topics": [
      "choking"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Choking (adult)",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "choking",
          "choke",
          "chokes",
          "heimlich",
          "abdominal thrust",
          "airway obstruction",
          "something stuck in throat"
        ]
      },
      "el": {
        "title": "Πνιγμονή από ξένο σώμα (ενήλικας)",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "πνιγμονη",
          "πνιγεται",
          "πνιγηκε",
          "ξενο σωμα",
          "heimlich",
          "χαιμλιχ",
          "κοιλιακες ωθησεις",
          "ασφυξια"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "burns",
    "topics": [
      "burn"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Burns",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "burn",
          "burns",
          "burned",
          "burnt",
          "scald",
          "scalded",
          "electric shock",
          "chemical burn"
        ]
      },
      "el": {
        "title": "Εγκαύματα",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "εγκαυμα",
          "εγκαυματα",
          "καψιμο",
          "καηκε",
          "ζεματισμα",
          "ηλεκτροπληξια",
          "χημικο εγκαυμα"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "fractures",
    "topics": [
      "fracture"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Broken bones (fractures)",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "fracture",
          "fractured",
          "broken bone",
          "broken arm",
          "broken leg",
          "splint",
          "sprain",
          "dislocation"
        ]
      },
      "el": {
        "title": "Κατάγματα",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "καταγμα",
          "καταγματα",
          "ναρθηκας",
          "διαστρεμμα",
          "εξαρθρημα"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "hypothermia",
    "topics": [
      "hypothermia"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Hypothermia (too cold)",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "hypothermia",
          "frostbite",
          "too cold",
          "freezing",
          "shivering",
          "cold exposure"
        ]
      },
      "el": {
        "title": "Υποθερμία (πολύ κρύο)",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "υποθερμια",
          "κρυοπαγημα",
          "παγωνει",
          "ριγος"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "heatstroke",
    "topics": [
      "heatstroke"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Heat stroke",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "heatstroke",
          "heat stroke",
          "sunstroke",
          "heat exhaustion",
          "overheated",
          "too hot"
        ]
      },
      "el": {
        "title": "Θερμοπληξία",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "θερμοπληξια",
          "ηλιαση",
          "θερμικη εξαντληση",
          "καυσωνας"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "poisoning",
    "topics": [
      "poisoning"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Poisoning",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "poison",
          "poisoning",
          "poisoned",
          "overdose",
          "swallowed",
          "toxic",
          "fumes",
          "carbon monoxide",
          "pesticide",
          "bleach"
        ]
      },
      "el": {
        "title": "Δηλητηρίαση",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "δηλητηριαση",
          "δηλητηριο",
          "υπερδοσολογια",
          "τοξικο",
          "αναθυμιασεις",
          "μονοξειδιο",
          "φυτοφαρμακο",
          "χλωρινη"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "water-purification",
    "topics": [],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Making water safe to drink",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "water purification",
          "purify water",
          "drinking water",
          "safe water",
          "boil water",
          "disinfect water",
          "bleach water",
          "treat water"
        ]
      },
      "el": {
        "title": "Πόσιμο νερό: πώς γίνεται ασφαλές",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "καθαρισμος νερου",
          "ποσιμο νερο",
          "βρασιμο νερου",
          "απολυμανση νερου",
          "χλωρινη νερο",
          "ασφαλες νερο"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "earthquake",
    "topics": [
      "earthquake"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Earthquake",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "earthquake",
          "quake",
          "aftershock",
          "drop cover hold"
        ]
      },
      "el": {
        "title": "Σεισμός",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "σεισμος",
          "σεισμου",
          "μετασεισμος",
          "πεσε καλυψου κρατησου"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "fire",
    "topics": [
      "fire"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Fire at home",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "fire",
          "house fire",
          "smoke",
          "flames",
          "burning building",
          "wildfire"
        ]
      },
      "el": {
        "title": "Φωτιά στο σπίτι",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "φωτια",
          "πυρκαγια",
          "φλογες",
          "καιγεται"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  },
  {
    "id": "flood",
    "topics": [
      "flood"
    ],
    "steps": [],
    "whenToCallForHelp": {
      "refs": []
    },
    "locales": {
      "en": {
        "title": "Flood",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "flood",
          "flooding",
          "flash flood",
          "rising water",
          "flood water"
        ]
      },
      "el": {
        "title": "Πλημμύρα",
        "steps": [],
        "whenToCallForHelp": "",
        "keywords": [
          "πλημμυρα",
          "πλημμυρες",
          "πλημμυρισε",
          "χειμαρρος"
        ]
      }
    },
    "review": {
      "status": "draft",
      "reviewers": [],
      "date": null
    }
  }
];
