import { CARDS } from './index';
import { CARD_LOCALES, type CardText, type EmergencyCard } from './schema';

/**
 * A card as Developer Preview builds ship it: no step text, no "when to call for help" text, no step
 * sources. The UI shows "Under professional review" and the emergency numbers instead.
 */
export function previewCard(card: EmergencyCard): EmergencyCard {
  const locales = Object.fromEntries(
    CARD_LOCALES.map((l) => {
      const text: CardText = { title: card.locales[l].title, steps: [], whenToCallForHelp: '', keywords: card.locales[l].keywords };
      return [l, text];
    }),
  ) as EmergencyCard['locales'];
  return { id: card.id, topics: card.topics, steps: [], whenToCallForHelp: { refs: [] }, locales, review: card.review };
}

/** Source of src/preview-cards.generated.ts (scripts/export-preview.ts). */
export function previewCardsSource(cards: readonly EmergencyCard[] = CARDS): string {
  return [
    '// Generated by scripts/export-preview.ts from the full cards. Do not edit.',
    '// Developer Preview builds bundle these cards (src/preview.ts): titles, topics, keywords and review',
    '// status only, no step text.',
    "import type { EmergencyCard } from './schema';",
    '',
    `export const PREVIEW_CARDS: readonly EmergencyCard[] = ${JSON.stringify(cards.map(previewCard), null, 2)};`,
    '',
  ].join('\n');
}
