// Release signing (CNG: android/ is regenerated by `expo prebuild --clean`, so it is wired here).
// - Release builds sign with the dedicated SKEPI keystore described by four Gradle properties,
//   normally kept in ~/.gradle/gradle.properties (never in the repo). See docs/release-signing.md.
// - Missing properties fail the release build before any compilation starts.
// - `-PskepiDebugSign=true` is the only escape hatch (local E2E): signs with the Expo debug key and
//   prints a loud warning. Such an APK must never be distributed.
const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = '// skepi:release-signing';

const GRADLE = `
${MARKER}
def skepiSigningKeys = [
    'SKEPI_RELEASE_STORE_FILE',
    'SKEPI_RELEASE_STORE_PASSWORD',
    'SKEPI_RELEASE_KEY_ALIAS',
    'SKEPI_RELEASE_KEY_PASSWORD',
]
def skepiProp = { String key -> (findProperty(key) ?: '').toString().trim() }
def skepiMissingKeys = skepiSigningKeys.findAll { skepiProp(it).isEmpty() }
def skepiStoreFile = skepiMissingKeys.contains('SKEPI_RELEASE_STORE_FILE') ? null : file(skepiProp('SKEPI_RELEASE_STORE_FILE'))
def skepiDebugSign = skepiProp('skepiDebugSign').toBoolean()
def skepiReleaseKeyReady = skepiMissingKeys.isEmpty() && skepiStoreFile != null && skepiStoreFile.isFile()

android {
    signingConfigs {
        if (skepiReleaseKeyReady) {
            skepiRelease {
                storeFile skepiStoreFile
                storePassword skepiProp('SKEPI_RELEASE_STORE_PASSWORD')
                keyAlias skepiProp('SKEPI_RELEASE_KEY_ALIAS')
                keyPassword skepiProp('SKEPI_RELEASE_KEY_PASSWORD')
            }
        }
    }
    buildTypes {
        release {
            // Overrides the template's debug signing. Null (unsigned) is never packaged:
            // skepiCheckReleaseSigning fails the build first.
            signingConfig skepiDebugSign ? signingConfigs.debug : (skepiReleaseKeyReady ? signingConfigs.skepiRelease : null)
        }
    }
}

def skepiCheckReleaseSigning = tasks.register('skepiCheckReleaseSigning') {
    doLast {
        if (skepiDebugSign) {
            def bar = '!' * 78
            logger.warn("\\n\${bar}\\n!! SKEPI: release build signed with the Expo DEBUG key (-PskepiDebugSign=true).\\n!! For local E2E only. NEVER distribute this APK.\\n\${bar}\\n")
            return
        }
        if (!skepiMissingKeys.isEmpty()) {
            throw new GradleException(
                "SKEPI release signing is not configured. Missing Gradle properties: \${skepiMissingKeys.join(', ')}.\\n" +
                "Add them to ~/.gradle/gradle.properties (see docs/release-signing.md), or pass\\n" +
                "-PskepiDebugSign=true for a local, debug-signed E2E build that must never be distributed.")
        }
        if (!skepiStoreFile.isFile()) {
            throw new GradleException(
                "SKEPI release keystore not found at SKEPI_RELEASE_STORE_FILE=\${skepiStoreFile}. See docs/release-signing.md.")
        }
        logger.lifecycle("SKEPI: release build signed with key alias '\${skepiProp('SKEPI_RELEASE_KEY_ALIAS')}' from \${skepiStoreFile.name}")
    }
}
tasks.matching { it.name == 'preReleaseBuild' }.configureEach { dependsOn skepiCheckReleaseSigning }
`;

module.exports = (config) =>
  withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes(MARKER)) return cfg;
    cfg.modResults.contents += GRADLE;
    return cfg;
  });
